In [ ]:
import pandas as pd
import numpy as np
from textblob import TextBlob
import plotly.graph_objects as go
import plotly.express as px

In [ ]:
mod1 = pd.read_csv("/content/modi_reviews.csv")
rahul = pd.read_csv("/content/rahul_reviews.csv")

In [ ]:
mod1.head()

,Unnamed: 0,User,Tweet
0,0,advosushildixit,@anjanaomkashyap I am seeing you as future #bj...
1,1,jiaeur,#LokSabhaElections2019 \n23rd May 2019 will re...
2,2,PVenkatGandhi,#LokSabhaElections2019 \n23rd May 2019 will re...
3,3,TheNirbhay1,PM Modi creates a new record of being the only...
4,4,ShakeChilli,@abhijitmajumder Appointment of Successor! \n\...

In [ ]:
rahul.head()

,Unnamed: 0,User,Tweet
0,0,Sunnysweet16,Wonder why no academic or journalist asks INC ...
1,1,drnitinchaube,Congrats for the change #australiavotes2019 an...
2,2,mrvivek07,Peopel Say “Govt Ne 70 Years Kya kiya”.\nUnse ...
3,3,JosephPravinP,"@ajaymaken @RahulGandhi And as a final touch, ..."
4,4,VandanaMegastar,#LokSabhaElections2019 Anyone not having mass ...

In [ ]:
mod1.tail()

,Unnamed: 0,User,Tweet
25683,25683,shv_indian,#1DDrive #ModiSpeaksToNews18 #LokSabhaElection...
25684,25684,SONUPINKOO,I am seriously worried about future of Indian ...
25685,25685,SONUPINKOO,If @narendramodi is so Bad then Why does @INCI...
25686,25686,SONUPINKOO,"On this 23rd March (Pakistan Day), I Urge all ..."
25687,25687,parthajit0101,"@timesofindia #ArvindKejriwal, #AAP sirji pls ..."

In [ ]:
mod1.shape

(25688, 3)

In [ ]:
rahul.shape

(14261, 3)

In [ ]:
rahul.tail()

,Unnamed: 0,User,Tweet
14256,14256,SunjayJK,"@quizzicalguy In this #LokSabhaElections2019, ..."
14257,14257,SunjayJK,@AnumaVidisha @RahulGandhi @ArvindKejriwal whe...
14258,14258,RAMANKAIRA,@sherryontopp Early morning #political move af...
14259,14259,RAMANKAIRA,@mayankgandhi04 @mallesh_2004 Early morning #p...
14260,14260,RAMANKAIRA,@DrKumarVishwas Early morning #political move ...

In [ ]:
TextBlob(mod1['Tweet'][10]).sentiment

Sentiment(polarity=0.0, subjectivity=0.0)

In [ ]:
TextBlob(rahul['Tweet'][10]).sentiment

Sentiment(polarity=-0.3814697265625, subjectivity=0.375)

In [ ]:
mod1['Tweet'] = mod1['Tweet'].astype(str)
rahul['Tweet'] = mod1['Tweet'].astype(str)

def find_polarity(review):
  return TextBlob(review).sentiment.polarity

In [ ]:
mod1['Polarity'] = mod1['Tweet'].apply(find_polarity)
rahul['Polarity'] = rahul['Tweet'].apply(find_polarity)

In [ ]:
mod1

,Unnamed: 0,User,Tweet,Polarity
0,0,advosushildixit,@anjanaomkashyap I am seeing you as future #bj...,0.350000
1,1,jiaeur,#LokSabhaElections2019 \n23rd May 2019 will re...,0.800000
2,2,PVenkatGandhi,#LokSabhaElections2019 \n23rd May 2019 will re...,0.800000
3,3,TheNirbhay1,PM Modi creates a new record of being the only...,0.312121
4,4,ShakeChilli,@abhijitmajumder Appointment of Successor! \n\...,0.098788
...,...,...,...,...
25683,25683,shv_indian,#1DDrive #ModiSpeaksToNews18 #LokSabhaElection...,0.000000
25684,25684,SONUPINKOO,I am seriously worried about future of Indian ...,0.209524
25685,25685,SONUPINKOO,If @narendramodi is so Bad then Why does @INCI...,-0.700000
25686,25686,SONUPINKOO,"On this 23rd March (Pakistan Day), I Urge all ...",0.000000
25687,25687,parthajit0101,"@timesofindia #ArvindKejriwal, #AAP sirji pls ...",-0.213542

In [ ]:
rahul

,Unnamed: 0,User,Tweet,Polarity
0,0,Sunnysweet16,@anjanaomkashyap I am seeing you as future #bj...,0.350000
1,1,drnitinchaube,#LokSabhaElections2019 \n23rd May 2019 will re...,0.800000
2,2,mrvivek07,#LokSabhaElections2019 \n23rd May 2019 will re...,0.800000
3,3,JosephPravinP,PM Modi creates a new record of being the only...,0.312121
4,4,VandanaMegastar,@abhijitmajumder Appointment of Successor! \n\...,0.098788
...,...,...,...,...
14256,14256,SunjayJK,@thewire_in @narendramodi It's a #BJP False Pr...,-0.400000
14257,14257,SunjayJK,#Mahagathbandhan This shows how much fear the...,0.300000
14258,14258,RAMANKAIRA,@BJP4UP @narendramodi Teacher: Give a to the p...,0.000000
14259,14259,RAMANKAIRA,I pledge to vote and support nation builder- N...,0.000000
14260,14260,RAMANKAIRA,#bjp #RahulGandhi Who is this Sambit Patra ......,0.000000

In [ ]:
def get_sentiment_label(polarity):
    if polarity > 0:
        return 'Positive'
    elif polarity < 0:
        return 'Negative'
    else:
        return 'Neutral'

rahul['Label'] = rahul['Polarity'].apply(get_sentiment_label)
rahul_count = rahul.groupby('Label').count()

In [ ]:
# Ensure 'Label' column exists for mod1 and calculate sentiment counts
mod1['Label'] = mod1['Polarity'].apply(get_sentiment_label)
mod1_count_by_label = mod1.groupby('Label').count()

# Get sentiment counts for Modi
neg_modi = mod1_count_by_label.loc['Negative', 'Tweet']
pos_modi = mod1_count_by_label.loc['Positive', 'Tweet']

# Get sentiment counts for Rahul (rahul_count is already by Label as per kernel state)
neg_rahul = rahul_count.loc['Negative', 'Tweet']
pos_rahul = rahul_count.loc['Positive', 'Tweet']

# Correct politician list syntax
politicians = ["Modi", "Rahul"]

# Create lists for plotting with correct variables
neg_list = [neg_modi, neg_rahul]
pos_list = [pos_modi, pos_rahul]

# Create the bar chart with corrected typos
fig = go.Figure(data=[
    go.Bar(name="Negative", x=politicians, y=neg_list),
    go.Bar(name="Positive", x=politicians, y=pos_list)
])
fig.show()